# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zlofey/testing/authentication.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthDialog(object):
    def setupUi(self, AuthDialog):
        AuthDialog.setObjectName("AuthDialog")
        AuthDialog.resize(372, 388)
        self.rememberMecheckBox = QtWidgets.QCheckBox(AuthDialog)
        self.rememberMecheckBox.setGeometry(QtCore.QRect(50, 220, 141, 21))
        self.rememberMecheckBox.setObjectName("rememberMecheckBox")
        self.showPassCheckBox = QtWidgets.QCheckBox(AuthDialog)
        self.showPassCheckBox.setGeometry(QtCore.QRect(50, 250, 131, 21))
        self.showPassCheckBox.setObjectName("showPassCheckBox")
        self.forgetPassButton = QtWidgets.QPushButton(AuthDialog)
        self.forgetPassButton.setGeometry(QtCore.QRect(30, 280, 141, 28))
        self.forgetPassButton.setStyleSheet("font: 10pt \"Ubuntu\";\n"
"text-decoration: underline;\n"
"color: rgb(0, 170, 255);\n"
"color: rgb(0, 96, 144)")
        self.forgetPassButton.setFlat(True)
        self.forgetPassButton.setObjectName("forgetPassButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(AuthDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 311, 98))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Username = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Username.setObjectName("Username")
        self.verticalLayout.addWidget(self.Username)
        self.Password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.verticalLayout.addWidget(self.Password)
        self.notifyLabel = QtWidgets.QLabel(AuthDialog)
        self.notifyLabel.setGeometry(QtCore.QRect(20, 180, 341, 31))
        self.notifyLabel.setStyleSheet("color: rgb(170, 0, 0); \n"
"font: 11pt \"Ubuntu\";")
        self.notifyLabel.setText("")
        self.notifyLabel.setObjectName("notifyLabel")
        self.enterButton = QtWidgets.QPushButton(AuthDialog)
        self.enterButton.setGeometry(QtCore.QRect(40, 130, 95, 28))
        self.enterButton.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: rgb(0, 0, 0);\n"
"")
        self.enterButton.setObjectName("enterButton")
        self.regButton = QtWidgets.QPushButton(AuthDialog)
        self.regButton.setGeometry(QtCore.QRect(140, 130, 121, 28))
        self.regButton.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"border: rgb(0, 0, 0);\n"
"")
        self.regButton.setObjectName("regButton")
        self.cancelButton = QtWidgets.QPushButton(AuthDialog)
        self.cancelButton.setGeometry(QtCore.QRect(270, 130, 81, 28))
        self.cancelButton.setStyleSheet("background-color: rgb(255, 115, 115); \n"
"border: rgb(159, 159, 159);")
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(AuthDialog)
        QtCore.QMetaObject.connectSlotsByName(AuthDialog)

    def retranslateUi(self, AuthDialog):
        _translate = QtCore.QCoreApplication.translate
        AuthDialog.setWindowTitle(_translate("AuthDialog", "Окно авторизации"))
        self.rememberMecheckBox.setText(_translate("AuthDialog", "Запомнить меня"))
        self.showPassCheckBox.setText(_translate("AuthDialog", "Показать пароль"))
        self.forgetPassButton.setText(_translate("AuthDialog", "Забыли пароль?"))
        self.Username.setPlaceholderText(_translate("AuthDialog", "Имя пользователя"))
        self.Password.setPlaceholderText(_translate("AuthDialog", "Пароль"))
        self.enterButton.setText(_translate("AuthDialog", "Войти"))
        self.regButton.setText(_translate("AuthDialog", "Регистрация"))
        self.cancelButton.setText(_translate("AuthDialog", "Отмена"))
