# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zlofey/testing/pass_reset.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pswdResetDialog(object):
    def setupUi(self, pswdResetDialog):
        pswdResetDialog.setObjectName("pswdResetDialog")
        pswdResetDialog.resize(400, 300)
        self.stackedWidget = QtWidgets.QStackedWidget(pswdResetDialog)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 0, 371, 281))
        self.stackedWidget.setObjectName("stackedWidget")
        self.requestPass = QtWidgets.QWidget()
        self.requestPass.setObjectName("requestPass")
        self.requestNotifyLabel = QtWidgets.QLabel(self.requestPass)
        self.requestNotifyLabel.setGeometry(QtCore.QRect(50, 170, 291, 41))
        self.requestNotifyLabel.setStyleSheet("color: rgb(170, 0, 0); \n"
"font: 11pt \"Ubuntu\";")
        self.requestNotifyLabel.setLineWidth(2)
        self.requestNotifyLabel.setText("")
        self.requestNotifyLabel.setObjectName("requestNotifyLabel")
        self.requestCancelButton = QtWidgets.QPushButton(self.requestPass)
        self.requestCancelButton.setGeometry(QtCore.QRect(60, 130, 111, 31))
        self.requestCancelButton.setStyleSheet("background-color: rgb(255, 115, 115); \n"
"border: rgb(159, 159, 159);")
        self.requestCancelButton.setObjectName("requestCancelButton")
        self.sendCode = QtWidgets.QPushButton(self.requestPass)
        self.sendCode.setGeometry(QtCore.QRect(190, 130, 111, 31))
        self.sendCode.setStyleSheet("background-color: rgb(176, 176, 176);\n"
"border: rgb(0, 0, 0);\n"
"")
        self.sendCode.setObjectName("sendCode")
        self.Email = QtWidgets.QLineEdit(self.requestPass)
        self.Email.setGeometry(QtCore.QRect(50, 90, 259, 28))
        self.Email.setText("")
        self.Email.setObjectName("Email")
        self.stackedWidget.addWidget(self.requestPass)
        self.confirmPass = QtWidgets.QWidget()
        self.confirmPass.setObjectName("confirmPass")
        self.okButton = QtWidgets.QPushButton(self.confirmPass)
        self.okButton.setGeometry(QtCore.QRect(190, 200, 111, 31))
        self.okButton.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: rgb(0, 0, 0);\n"
"")
        self.okButton.setObjectName("okButton")
        self.confirmCancelButton = QtWidgets.QPushButton(self.confirmPass)
        self.confirmCancelButton.setGeometry(QtCore.QRect(60, 200, 111, 31))
        self.confirmCancelButton.setStyleSheet("background-color: rgb(255, 115, 115); \n"
"border: rgb(159, 159, 159);")
        self.confirmCancelButton.setObjectName("confirmCancelButton")
        self.confirmNotifyLabel = QtWidgets.QLabel(self.confirmPass)
        self.confirmNotifyLabel.setGeometry(QtCore.QRect(60, 160, 241, 31))
        self.confirmNotifyLabel.setStyleSheet("color: rgb(170, 0, 0); \n"
"font: 11pt \"Ubuntu\";")
        self.confirmNotifyLabel.setText("")
        self.confirmNotifyLabel.setObjectName("confirmNotifyLabel")
        self.Password = QtWidgets.QLineEdit(self.confirmPass)
        self.Password.setGeometry(QtCore.QRect(50, 80, 259, 28))
        self.Password.setText("")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.PasswordConfirm = QtWidgets.QLineEdit(self.confirmPass)
        self.PasswordConfirm.setGeometry(QtCore.QRect(50, 128, 259, 28))
        self.PasswordConfirm.setText("")
        self.PasswordConfirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordConfirm.setObjectName("PasswordConfirm")
        self.Code = QtWidgets.QLineEdit(self.confirmPass)
        self.Code.setGeometry(QtCore.QRect(50, 30, 261, 28))
        self.Code.setObjectName("Code")
        self.stackedWidget.addWidget(self.confirmPass)

        self.retranslateUi(pswdResetDialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(pswdResetDialog)

    def retranslateUi(self, pswdResetDialog):
        _translate = QtCore.QCoreApplication.translate
        pswdResetDialog.setWindowTitle(_translate("pswdResetDialog", "Восстановление пароля"))
        self.requestCancelButton.setText(_translate("pswdResetDialog", "Отмена"))
        self.sendCode.setText(_translate("pswdResetDialog", "Отправить код"))
        self.Email.setPlaceholderText(_translate("pswdResetDialog", "Адрес электронной почты"))
        self.okButton.setText(_translate("pswdResetDialog", "Сменить пароль"))
        self.confirmCancelButton.setText(_translate("pswdResetDialog", "Отмена"))
        self.Password.setPlaceholderText(_translate("pswdResetDialog", "Новый пароль"))
        self.PasswordConfirm.setPlaceholderText(_translate("pswdResetDialog", "Подтверждение пароля"))
        self.Code.setPlaceholderText(_translate("pswdResetDialog", "Код"))
