# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zlofey/testing/phone_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PhoneBook(object):
    def setupUi(self, PhoneBook):
        PhoneBook.setObjectName("PhoneBook")
        PhoneBook.resize(794, 706)
        self.centralwidget = QtWidgets.QWidget(PhoneBook)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(130, 40, 631, 541))
        self.tableWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setGeometry(QtCore.QRect(230, 0, 281, 31))
        self.usernameLabel.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.usernameLabel.setText("")
        self.usernameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.usernameLabel.setObjectName("usernameLabel")
        self.tabsTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tabsTableWidget.setGeometry(QtCore.QRect(70, 40, 51, 431))
        self.tabsTableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tabsTableWidget.setRowCount(0)
        self.tabsTableWidget.setColumnCount(0)
        self.tabsTableWidget.setObjectName("tabsTableWidget")
        self.tabsTableWidget.verticalHeader().setVisible(False)
        self.tabsTableWidget.verticalHeader().setStretchLastSection(True)
        self.deletePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.deletePushButton.setGeometry(QtCore.QRect(190, 600, 101, 28))
        self.deletePushButton.setStyleSheet("background-color: rgb(255, 115, 115); \n"
"border: rgb(159, 159, 159);")
        self.deletePushButton.setObjectName("deletePushButton")
        self.updatePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.updatePushButton.setGeometry(QtCore.QRect(380, 600, 111, 28))
        self.updatePushButton.setStyleSheet("background-color: rgb(255, 250, 184);\n"
"border: rgb(0, 0, 0);\n"
"")
        self.updatePushButton.setObjectName("updatePushButton")
        self.createPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.createPushButton.setGeometry(QtCore.QRect(579, 600, 91, 28))
        self.createPushButton.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: rgb(0, 0, 0);\n"
"")
        self.createPushButton.setObjectName("createPushButton")
        self.notifyLabel = QtWidgets.QLabel(self.centralwidget)
        self.notifyLabel.setGeometry(QtCore.QRect(190, 640, 481, 31))
        self.notifyLabel.setStyleSheet("color: rgb(170, 0, 0); \n"
"font: 11pt \"Ubuntu\";")
        self.notifyLabel.setText("")
        self.notifyLabel.setObjectName("notifyLabel")
        self.logoutPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutPushButton.setGeometry(QtCore.QRect(630, 0, 101, 28))
        self.logoutPushButton.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"border: rgb(0, 0, 0);\n"
"")
        self.logoutPushButton.setObjectName("logoutPushButton")
        PhoneBook.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PhoneBook)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 22))
        self.menubar.setObjectName("menubar")
        PhoneBook.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PhoneBook)
        self.statusbar.setObjectName("statusbar")
        PhoneBook.setStatusBar(self.statusbar)

        self.retranslateUi(PhoneBook)
        QtCore.QMetaObject.connectSlotsByName(PhoneBook)

    def retranslateUi(self, PhoneBook):
        _translate = QtCore.QCoreApplication.translate
        PhoneBook.setWindowTitle(_translate("PhoneBook", "Телефонная книжка"))
        self.deletePushButton.setText(_translate("PhoneBook", "Удалить"))
        self.updatePushButton.setText(_translate("PhoneBook", "Редактировать"))
        self.createPushButton.setText(_translate("PhoneBook", "Добавить"))
        self.logoutPushButton.setText(_translate("PhoneBook", "Выйти"))
