# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zlofey/testing/registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationQDialog(object):
    def setupUi(self, RegistrationQDialog):
        RegistrationQDialog.setObjectName("RegistrationQDialog")
        RegistrationQDialog.resize(373, 387)
        self.verticalLayoutWidget = QtWidgets.QWidget(RegistrationQDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 20, 261, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Username = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Username.setObjectName("Username")
        self.verticalLayout.addWidget(self.Username)
        self.Email = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Email.setText("")
        self.Email.setObjectName("Email")
        self.verticalLayout.addWidget(self.Email)
        self.Password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Password.setText("")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.verticalLayout.addWidget(self.Password)
        self.PasswordConfirm = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.PasswordConfirm.setText("")
        self.PasswordConfirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordConfirm.setObjectName("PasswordConfirm")
        self.verticalLayout.addWidget(self.PasswordConfirm)
        self.BirthDate = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.BirthDate.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.BirthDate.setWrapping(False)
        self.BirthDate.setFrame(True)
        self.BirthDate.setSpecialValueText("")
        self.BirthDate.setProperty("showGroupSeparator", False)
        self.BirthDate.setCalendarPopup(True)
        self.BirthDate.setObjectName("BirthDate")
        self.verticalLayout.addWidget(self.BirthDate)
        self.cancelButton = QtWidgets.QPushButton(RegistrationQDialog)
        self.cancelButton.setGeometry(QtCore.QRect(60, 330, 111, 31))
        self.cancelButton.setStyleSheet("background-color: rgb(255, 115, 115); \n"
"border: rgb(159, 159, 159);")
        self.cancelButton.setObjectName("cancelButton")
        self.okButton = QtWidgets.QPushButton(RegistrationQDialog)
        self.okButton.setGeometry(QtCore.QRect(190, 330, 111, 31))
        self.okButton.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: rgb(0, 0, 0);\n"
"")
        self.okButton.setObjectName("okButton")
        self.notifyLabel = QtWidgets.QLabel(RegistrationQDialog)
        self.notifyLabel.setGeometry(QtCore.QRect(60, 280, 241, 31))
        self.notifyLabel.setStyleSheet("color: rgb(170, 0, 0); \n"
"font: 11pt \"Ubuntu\";")
        self.notifyLabel.setText("")
        self.notifyLabel.setObjectName("notifyLabel")

        self.retranslateUi(RegistrationQDialog)
        QtCore.QMetaObject.connectSlotsByName(RegistrationQDialog)

    def retranslateUi(self, RegistrationQDialog):
        _translate = QtCore.QCoreApplication.translate
        RegistrationQDialog.setWindowTitle(_translate("RegistrationQDialog", "Регистрация"))
        self.Username.setPlaceholderText(_translate("RegistrationQDialog", "Имя пользователя"))
        self.Email.setPlaceholderText(_translate("RegistrationQDialog", "Email"))
        self.Password.setPlaceholderText(_translate("RegistrationQDialog", "Пароль"))
        self.PasswordConfirm.setPlaceholderText(_translate("RegistrationQDialog", "Подтверждение пароля"))
        self.BirthDate.setDisplayFormat(_translate("RegistrationQDialog", "d.M.yyyy"))
        self.cancelButton.setText(_translate("RegistrationQDialog", "Отмена"))
        self.okButton.setText(_translate("RegistrationQDialog", "Ок"))
