# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zlofey/testing/update_contact_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdateContactDialog(object):
    def setupUi(self, UpdateContactDialog):
        UpdateContactDialog.setObjectName("UpdateContactDialog")
        UpdateContactDialog.resize(298, 297)
        self.verticalLayoutWidget = QtWidgets.QWidget(UpdateContactDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 241, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.name.setPlaceholderText("")
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.phone = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.phone.setText("")
        self.phone.setPlaceholderText("")
        self.phone.setObjectName("phone")
        self.verticalLayout.addWidget(self.phone)
        self.birthDate = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.birthDate.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.birthDate.setWrapping(False)
        self.birthDate.setFrame(True)
        self.birthDate.setSpecialValueText("")
        self.birthDate.setProperty("showGroupSeparator", False)
        self.birthDate.setCalendarPopup(True)
        self.birthDate.setObjectName("birthDate")
        self.verticalLayout.addWidget(self.birthDate)
        self.cancelButton = QtWidgets.QPushButton(UpdateContactDialog)
        self.cancelButton.setGeometry(QtCore.QRect(30, 230, 111, 31))
        self.cancelButton.setStyleSheet("background-color: rgb(255, 115, 115); \n"
"border: rgb(159, 159, 159);")
        self.cancelButton.setObjectName("cancelButton")
        self.okButton = QtWidgets.QPushButton(UpdateContactDialog)
        self.okButton.setGeometry(QtCore.QRect(160, 230, 111, 31))
        self.okButton.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"border: rgb(0, 0, 0);\n"
"")
        self.okButton.setObjectName("okButton")
        self.notifyLabel = QtWidgets.QLabel(UpdateContactDialog)
        self.notifyLabel.setGeometry(QtCore.QRect(30, 190, 241, 31))
        self.notifyLabel.setStyleSheet("color: rgb(170, 0, 0); \n"
"font: 11pt \"Ubuntu\";")
        self.notifyLabel.setText("")
        self.notifyLabel.setObjectName("notifyLabel")

        self.retranslateUi(UpdateContactDialog)
        QtCore.QMetaObject.connectSlotsByName(UpdateContactDialog)

    def retranslateUi(self, UpdateContactDialog):
        _translate = QtCore.QCoreApplication.translate
        UpdateContactDialog.setWindowTitle(_translate("UpdateContactDialog", "Редактировать контакт"))
        self.birthDate.setDisplayFormat(_translate("UpdateContactDialog", "d.M.yyyy"))
        self.cancelButton.setText(_translate("UpdateContactDialog", "Отмена"))
        self.okButton.setText(_translate("UpdateContactDialog", "Ок"))
